# Generated by Django 3.2.3 on 2021-06-04 18:18

from django.db import migrations, models

import api.fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=api.fields.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='place',
            name='chosen',
            field=models.BooleanField(default=False, verbose_name='Отображать'),
            preserve_default=False,
        ),
    ]
