# Generated by Django 3.2.3 on 2021-06-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='events',
        ),
    ]
