# Generated by Django 3.2.3 on 2021-06-04 01:57

import api.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='color',
            field=api.fields.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет'),
        ),
    ]
