# Generated by Django 3.2.3 on 2021-06-07 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210605_0125'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Main',
        ),
    ]
