# Generated by Django 3.2.3 on 2021-06-07 13:47

from django.db import migrations, models

import api.fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('color', api.fields.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('output_to_main', models.BooleanField(verbose_name='Отображать на главной странице')),
                ('tags', models.ManyToManyField(related_name='rights', to='api.Tag', verbose_name='Тег(и)')),
            ],
            options={
                'verbose_name': 'Право',
                'verbose_name_plural': 'Права',
                'ordering': ('id',),
            },
        ),
    ]
