# Generated by Django 3.2.3 on 2021-06-07 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_right'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='output_to_main',
        ),
    ]
