# Generated by Django 3.2.3 on 2021-06-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_right_output_to_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='api.Tag', verbose_name='Тег(и)'),
        ),
    ]
