# Generated by Django 3.2.3 on 2021-06-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_place_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='activity_type',
            field=models.CharField(default='активный отдых', max_length=200, verbose_name='Вид активности'),
            preserve_default=False,
        ),
    ]
