# Generated by Django 3.2.3 on 2021-06-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210608_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
            preserve_default=False,
        ),
    ]
