# Generated by Django 3.2.3 on 2021-06-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210608_0418'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
        migrations.AddField(
            model_name='history',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
        migrations.AddField(
            model_name='movie',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
        migrations.AddField(
            model_name='video',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='place',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='question',
            name='output_to_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной странице'),
        ),
    ]
