# Generated by Django 3.2.3 on 2021-06-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210608_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='info',
        ),
        migrations.RemoveField(
            model_name='place',
            name='name',
        ),
        migrations.AddField(
            model_name='place',
            name='age',
            field=models.SmallIntegerField(default=10, verbose_name='Пол ребёнка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='sex',
            field=models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], default=1, max_length=6, verbose_name='Пол ребёнка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
