# Generated by Django 3.2.3 on 2021-06-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_place_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='activity_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='api.activitytype', verbose_name='Вид активности'),
            preserve_default=False,
        ),
    ]
