# Generated by Django 3.2.3 on 2021-06-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_place_activity_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={'ordering': ('id',), 'verbose_name': 'Тип отдыха', 'verbose_name_plural': 'Типы отдыха'},
        ),
        migrations.AlterField(
            model_name='activitytype',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Вид активности'),
        ),
    ]
