# Generated by Django 3.2.3 on 2021-06-11 12:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0015_auto_20210609_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='sex',
            new_name='gender',
        ),
        migrations.AddField(
            model_name='history',
            name='child',
            field=models.CharField(default='Никита', max_length=100, verbose_name='Имя ребёнка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='description',
            field=models.TextField(default='Текст истории', verbose_name='Текст истории'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='mentor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.customuser', verbose_name='Наставник'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='together_since',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='history',
            constraint=models.UniqueConstraint(fields=('mentor', 'child'), name='mentor_and_child_uniq_together'),
        ),
    ]
