# Generated by Django 3.2.3 on 2021-06-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_video_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tags',
            field=models.ManyToManyField(related_name='movies', to='api.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(related_name='videos', to='api.Tag', verbose_name='Теги'),
        ),
    ]
