# Generated by Django 3.2.3 on 2021-06-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20210611_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='annotation',
            field=models.TextField(default='Аннотация фильма', max_length=1024, verbose_name='Аннотация'),
            preserve_default=False,
        ),
    ]
