# Generated by Django 3.2.3 on 2021-06-20 08:35

from django.db import migrations, models

import api.fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210620_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('info', models.CharField(max_length=256, verbose_name='Информация')),
                ('annotation', models.TextField(max_length=1024, verbose_name='Аннотация')),
                ('color', api.fields.fields.ColorField(default='#FF0000', max_length=7, verbose_name='Цвет')),
                ('output_to_main', models.BooleanField(default=False, verbose_name='Отображать на главной странице')),
                ('tags', models.ManyToManyField(related_name='books', to='api.Tag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ('id',),
            },
        ),
    ]
