# Generated by Django 3.2.3 on 2021-06-20 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='output_to_main',
        ),
    ]
