# Generated by Django 3.2.3 on 2021-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_book_output_to_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=128, verbose_name='Место встречи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.TextField(max_length=1024, verbose_name='Описание встречи')),
                ('image_url', models.URLField(blank=True, max_length=192, verbose_name='Ссылка на изображение')),
                ('mark', models.CharField(choices=[('bad', 'Плохо'), ('good', 'Хорошо'), ('neutral', 'Нейтрально')], max_length=15, verbose_name='Как прошло время')),
            ],
            options={
                'verbose_name': 'Дневник',
                'verbose_name_plural': 'Дневники',
                'ordering': ('-date',),
            },
        ),
    ]
