# Generated by Django 3.2.3 on 2021-06-20 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_diary_mentor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('image_url', models.URLField(max_length=192, verbose_name='Ссылка на изображение')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочник',
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='diary',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
