# Generated by Django 3.2.3 on 2021-06-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210620_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='together_since',
            field=models.DateField(verbose_name='Вместе с'),
        ),
    ]
