# Generated by Django 3.2.3 on 2021-06-22 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_history_together_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('category', 'name'), 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Книги', 'Книги'), ('Фильмы', 'Фильмы'), ('Места', 'Места'), ('Вопросы', 'Вопросы'), ('Права', 'Права'), ('Видеоролики', 'Видеоролики')], default='Книги', max_length=50, verbose_name='Категория тега'),
            preserve_default=False,
        ),
    ]
