# Generated by Django 3.2.3 on 2021-06-23 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_place_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='image',
            new_name='_image',
        ),
    ]
