# Generated by Django 3.2.3 on 2021-06-23 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_rename_image_place__image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='_image',
            new_name='image',
        ),
    ]
