# Generated by Django 3.2.3 on 2021-06-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_video_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image_url',
        ),
        migrations.AddField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diaries/', verbose_name='Изображение'),
        ),
    ]
