# Generated by Django 3.2.3 on 2021-06-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210623_2321'),
        ('api', '0030_rename__image_place_image'),
    ]

    operations = [
    ]
