# Generated by Django 3.2.3 on 2021-06-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalogs/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='right',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rights/', verbose_name='Фото'),
        ),
    ]
