# Generated by Django 3.2.3 on 2021-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210625_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='color',
        ),
        migrations.RemoveField(
            model_name='history',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='right',
            name='color',
        ),
        migrations.RemoveField(
            model_name='right',
            name='image',
        ),
        migrations.RemoveField(
            model_name='right',
            name='image_url',
        ),
        migrations.AddField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='history/', verbose_name='Изображение'),
        ),
    ]
