# Generated by Django 3.2.3 on 2021-06-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_movie_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='url',
            field=models.URLField(default='https://www.ozon.ru/product/zhizn-posle-utraty-psihologiya-gorevaniya-263810177/', verbose_name='Ссылка'),
            preserve_default=False,
        ),
    ]
