# Generated by Django 3.2.3 on 2021-06-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_auto_20210629_0424'),
        ('api', '0039_book_url'),
    ]

    operations = [
    ]
