# Generated by Django 3.2.3 on 2021-06-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_merge_0039_auto_20210629_0424_0039_book_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_url',
            field=models.URLField(default='https://studwood.ru/1853536/pedagogika/harakteristika_sotsialnyh_detey_sirot_raznogo_vozrasta', max_length=192, verbose_name='Ссылка на статью'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booktype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг'),
        ),
    ]
