# Generated by Django 3.2.3 on 2021-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_auto_20210630_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='age_restriction',
            field=models.CharField(choices=[('8-10', '8-10'), ('11-13', '11-13'), ('14-17', '14-17'), ('18+', '18+'), ('Без ограничений', 'Без ограничений')], default='18+', max_length=50, verbose_name='Возрастные ограничения'),
            preserve_default=False,
        ),
    ]
