# Generated by Django 3.2.3 on 2021-07-04 08:16

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_place_age_restriction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='info',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Волкан Вамик', max_length=256, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.SmallIntegerField(default=2003, validators=[api.validators.year_validator], verbose_name='Год публикации'),
            preserve_default=False,
        ),
    ]
