# Generated by Django 3.2.3 on 2021-07-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_event_seats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.tag', verbose_name='Тег(и)'),
            preserve_default=False,
        ),
    ]
