# Generated by Django 3.2.3 on 2021-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_auto_20210704_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pinned_full_size',
            field=models.BooleanField(default=False, verbose_name='Отображать с полноразмерным изображением вверху страницы'),
        ),
        migrations.AddField(
            model_name='video',
            name='pinned_full_size',
            field=models.BooleanField(default=False, verbose_name='Отображать с полноразмерным видео вверху страницы'),
        ),
    ]
