# Generated by Django 3.2.3 on 2021-07-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_tag_name'),
        ('api', '0048_auto_20210704_1826'),
    ]

    operations = [
    ]
