# Generated by Django 3.2.3 on 2021-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_merge_0048_alter_tag_name_0048_auto_20210704_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, max_length=192, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
