# Generated by Django 3.2.3 on 2021-07-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='resource_group',
            field=models.BooleanField(default=False, verbose_name='Ресурсная группа'),
        ),
    ]
