# Generated by Django 3.2.3 on 2021-07-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_alter_article_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='content',
            field=models.TextField(default='<br>', verbose_name='Содержание статьи'),
            preserve_default=False,
        ),
    ]
