# Generated by Django 3.2.3 on 2021-07-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_catalog_content'),
        ('api', '0051_video_resource_group'),
    ]

    operations = [
    ]
