# Generated by Django 3.2.3 on 2021-07-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_video_resource_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='right',
            name='raw_html',
            field=models.TextField(default='<span>empty</span>', max_length=4000000, verbose_name='HTML'),
            preserve_default=False,
        ),
    ]
