# Generated by Django 3.2.3 on 2021-07-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_right_raw_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='content',
            field=models.TextField(),
        ),
    ]
