# Generated by Django 3.2.3 on 2021-07-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_auto_20210714_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='blocking_view',
        ),
        migrations.AddField(
            model_name='place',
            name='moderation_flag',
            field=models.BooleanField(default=False, verbose_name='Отметка о модерации'),
        ),
    ]
