# Generated by Django 3.2.3 on 2021-07-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_alter_place_age_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Сайт'),
        ),
    ]
