# Generated by Django 3.2.3 on 2021-07-16 12:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_alter_place_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)], verbose_name='Возраст ребёнка'),
        ),
    ]
