# Generated by Django 3.2.3 on 2021-07-16 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_place_age'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('place', 'date', 'mentor'), name='diary_place_date_uniquetogether'),
        ),
    ]
