# Generated by Django 3.2.3 on 2021-07-18 08:21

import api.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_auto_20210717_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='articles/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернативный способ загрузки изображения.                      Приоритет у файла.', max_length=192, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Статьи с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Статья с этой меткой будет отображаться                      в полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.URLField(verbose_name='Ссылка на книгу'),
        ),
        migrations.AlterField(
            model_name='booktype',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Слаг (Ссылка)'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='catalogs/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image_url',
            field=models.URLField(help_text='Альтернативный способ загрузки изображения.                      Приоритет у файла.', max_length=192, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='raw_html',
            field=models.TextField(help_text='Поле для html кода страницы.', max_length=4000000, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Города с этой меткой будут отображаться                      в начале списка.', verbose_name='Приоритет вывода'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='diaries/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='history/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='history',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Истории с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='history',
            name='raw_html',
            field=models.TextField(help_text='Поле для html кода страницы.', max_length=4000000, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='movies/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Фильмы с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='places/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернативный способ загрузки изображения.                      Приоритет у файла.', null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='place',
            name='moderation_flag',
            field=models.BooleanField(default=False, help_text='Места без этой метки не будут отображаться                      на сайте.', verbose_name='Отметка о модерации'),
        ),
        migrations.AlterField(
            model_name='place',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Места с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='question',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Вопросы с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='right',
            name='raw_html',
            field=models.TextField(help_text='Поле для html кода страницы.', max_length=4000000, verbose_name='HTML'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Книги', 'Книги'), ('Фильмы', 'Фильмы'), ('Места', 'Места'), ('Вопросы', 'Вопросы'), ('Права', 'Права'), ('Видеоролики', 'Видеоролики'), ('События', 'События')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)], verbose_name='Длина видео в сек.'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp.              Размер до 10М.', null=True, upload_to='videos/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='video',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой будут отображаться                      на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой будет отображаться                      в полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='video',
            name='resource_group',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой не будут показаны                      не авторизованным пользователям.', verbose_name='Ресурсная группа'),
        ),
    ]
