# Generated by Django 3.2.3 on 2021-07-18 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0063_auto_20210718_0425'),
        ('api', '0063_auto_20210718_1521'),
    ]

    operations = [
    ]
