# Generated by Django 3.2.3 on 2021-07-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_merge_0063_auto_20210718_0425_0063_auto_20210718_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='sent_to_curator',
            field=models.BooleanField(default=False, help_text='Метка о факте отправки дневника куратору.', verbose_name='Отпралено куратору'),
        ),
    ]
