# Generated by Django 3.2.3 on 2021-08-12 12:34

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_diary_sent_to_curator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='raw_html',
        ),
        migrations.AddField(
            model_name='catalog',
            name='body',
            field=martor.models.MartorField(default='some text', verbose_name='Текст статьи'),
            preserve_default=False,
        ),
    ]
