# Generated by Django 3.2.3 on 2021-08-12 15:34

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_auto_20210812_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description',
            field=models.TextField(default='Верхний абзац', help_text='Отображается над изображением', max_length=1024, verbose_name='Верхний абзац'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='body',
            field=martor.models.MartorField(help_text='Основной текст статьи. Пожалуйста, используйте форматирование.', verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image_url',
            field=models.URLField(help_text='Альтернативный способ загрузки изображения. Приоритет у файла.', max_length=192, verbose_name='Ссылка на изображение'),
        ),
    ]
