# Generated by Django 3.2.3 on 2021-08-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_textblock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='raw_html',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text',
        ),
        migrations.AddField(
            model_name='right',
            name='list_block',
            field=models.TextField(blank=True, verbose_name='Список тезисов'),
        ),
        migrations.AddField(
            model_name='right',
            name='text_blocks',
            field=models.ManyToManyField(related_name='rights', to='api.TextBlock', verbose_name='Абзацы'),
        ),
    ]
