# Generated by Django 3.2.3 on 2021-08-10 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20210809_2231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='textblock',
            options={'ordering': ('order',), 'verbose_name': 'Блок текста', 'verbose_name_plural': 'Блоки текста'},
        ),
        migrations.RemoveField(
            model_name='right',
            name='list_block',
        ),
        migrations.RemoveField(
            model_name='right',
            name='text_blocks',
        ),
        migrations.RemoveField(
            model_name='textblock',
            name='title',
        ),
        migrations.CreateModel(
            name='RightContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('text', 'Абзац'), ('list', 'Список')], max_length=4, verbose_name='Тип контента')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок вывода')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rights', to='api.right', verbose_name='Статья')),
                ('text_blocks', models.ManyToManyField(related_name='rights', to='api.TextBlock', verbose_name='Блоки текста')),
            ],
            options={
                'verbose_name': 'Содержание статьи',
                'verbose_name_plural': 'Содержание статьи',
                'ordering': ('order',),
            },
        ),
        migrations.AddField(
            model_name='right',
            name='content',
            field=models.ManyToManyField(related_name='rights', to='api.RightContent', verbose_name='Контент'),
        ),
    ]
