# Generated by Django 3.2.3 on 2021-08-14 13:15

import api.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_auto_20210812_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='articles/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image_url',
            field=models.URLField(blank=True, help_text='Альтернативный способ загрузки изображения. Приоритет у файла.', max_length=192, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='article',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Статьи с этой меткой будут отображаться на главной странице.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Статья с этой меткой будет отображатьсяв полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='description',
            field=models.TextField(help_text='Отображается над изображением.', max_length=1024, verbose_name='Верхний абзац'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='catalogs/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='Города с этой меткой будут отображаться в начале списка.', verbose_name='Приоритет вывода'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='diaries/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tags',
            field=models.ForeignKey(limit_choices_to={'category': 'События'}, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api.tag', verbose_name='Тег'),
        ),
        migrations.AlterField(
            model_name='history',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='history/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='history',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Истории с этой меткой будут отображаться на главной странице.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='movies/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Фильмы с этой меткой будут отображаться на главной странице.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='place',
            name='moderation_flag',
            field=models.BooleanField(default=False, help_text='Места без этой метки не будут отображаться на сайте.', verbose_name='Отметка о модерации'),
        ),
        migrations.AlterField(
            model_name='place',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Места с этой меткой будут отображаться на главной странице сайта.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='question',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Вопросы с этой меткой будут отображаться на главной странице.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='category',
            field=models.CharField(choices=[('Фильмы', 'Фильмы'), ('Места', 'Места'), ('Вопросы', 'Вопросы'), ('Права', 'Права'), ('Видеоролики', 'Видеоролики'), ('События', 'События')], max_length=50, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='videos/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='video',
            name='output_to_main',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой будут отображаться на главной странице.', verbose_name='Отображать на главной странице'),
        ),
        migrations.AlterField(
            model_name='video',
            name='pinned_full_size',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой будет отображатьсяв полноразмерном формате вверху страницы.', verbose_name='Закрепить'),
        ),
        migrations.AlterField(
            model_name='video',
            name='resource_group',
            field=models.BooleanField(default=False, help_text='Видео с этой меткой не будут показаныне авторизованным пользователям.', verbose_name='Ресурсная группа'),
        ),
    ]
