# Generated by Django 3.2.3 on 2021-08-19 13:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20210814_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('id',), 'permissions': (('events_in_all_cities', 'Можно смотреть события всех городов'),), 'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ('id',), 'permissions': (('places_in_all_cities', 'Можно смотреть места всех городов'),), 'verbose_name': 'Куда пойти', 'verbose_name_plural': 'Куда пойти'},
        ),
        migrations.AlterField(
            model_name='place',
            name='activity_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='places', to='api.activitytype', verbose_name='Вид активности'),
        ),
        migrations.AlterField(
            model_name='place',
            name='age',
            field=models.SmallIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(25)], verbose_name='Возраст ребёнка'),
        ),
        migrations.AlterField(
            model_name='place',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=6, verbose_name='Пол ребёнка'),
        ),
    ]
