# Generated by Django 3.2.3 on 2021-08-10 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_auto_20210810_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='right',
            name='content',
        ),
    ]
