# Generated by Django 3.2.3 on 2021-08-20 07:54

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_auto_20210820_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('-id',), 'verbose_name': 'Справочник', 'verbose_name_plural': 'Справочник'},
        ),
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, help_text='Поддерживаемые форматы jpg, jpeg, gif, png, bmp. Размер до 10 Мб.', null=True, upload_to='catalog/', validators=[api.validators.file_size_validator, api.validators.image_extension_validator], verbose_name='Изображение'),
        ),
    ]
