# Generated by Django 3.2.3 on 2021-08-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_rightcontent_right'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rightcontent',
            old_name='type',
            new_name='block_type',
        ),
        migrations.RemoveField(
            model_name='rightcontent',
            name='text_blocks',
        ),
        migrations.AddField(
            model_name='rightcontent',
            name='colored_back',
            field=models.BooleanField(default=False, verbose_name='Раскрашенный фон'),
        ),
    ]
