# Generated by Django 3.2.3 on 2021-08-11 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20210811_2042'),
    ]

    database_operations = [migrations.AlterModelTable('TextBlock', 'common_textblock')]

    state_operations = [migrations.DeleteModel('TextBlock')]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
