# Generated by Django 3.2.3 on 2021-08-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0071_auto_20210820_1454'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='right',
            options={'ordering': ('-id',), 'verbose_name': 'Право', 'verbose_name_plural': 'Права'},
        ),
    ]
