# Generated by Django 3.2.3 on 2021-08-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('api', '0072_auto_20210811_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='rightcontent',
            name='text_blocks',
            field=models.ManyToManyField(related_name='rights', to='common.TextBlock', verbose_name='Блоки текста'),
        ),
    ]
