# Generated by Django 3.2.3 on 2021-07-15 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_is_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to=settings.AUTH_USER_MODEL, verbose_name='Куратор'),
        ),
    ]
